// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG3Qf6HmpMdQBEkftvhOEEfNwpVZDCzGE',
    appId: '1:562431488935:web:6ac35907065443ffe27c82',
    messagingSenderId: '562431488935',
    projectId: 'pharmacybenz',
    authDomain: 'pharmacybenz.firebaseapp.com',
    storageBucket: 'pharmacybenz.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF6qDxeV1xo7qBYgLqkJOv_yz1vIY2flE',
    appId: '1:562431488935:android:aa2587737296395ae27c82',
    messagingSenderId: '562431488935',
    projectId: 'pharmacybenz',
    storageBucket: 'pharmacybenz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLN3ybZ_gORAeEK7NFkDlT_uq6mRsOGfI',
    appId: '1:562431488935:ios:b68b088ed159fa2ae27c82',
    messagingSenderId: '562431488935',
    projectId: 'pharmacybenz',
    storageBucket: 'pharmacybenz.firebasestorage.app',
    iosBundleId: 'com.example.pharmacyBenz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLN3ybZ_gORAeEK7NFkDlT_uq6mRsOGfI',
    appId: '1:562431488935:ios:b68b088ed159fa2ae27c82',
    messagingSenderId: '562431488935',
    projectId: 'pharmacybenz',
    storageBucket: 'pharmacybenz.firebasestorage.app',
    iosBundleId: 'com.example.pharmacyBenz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDG3Qf6HmpMdQBEkftvhOEEfNwpVZDCzGE',
    appId: '1:562431488935:web:80d9630be498d47de27c82',
    messagingSenderId: '562431488935',
    projectId: 'pharmacybenz',
    authDomain: 'pharmacybenz.firebaseapp.com',
    storageBucket: 'pharmacybenz.firebasestorage.app',
  );
}
